name: Software Fuzzing Analysis

on: ["push"]

jobs:
  software-fuzzing-analysis:
    name: Software Fuzzing Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Install Required Package
        run: pip install ruamel.yaml

      - name: Run Fuzzing Analysis
        run: python KubeSec-master/fuzz.py
